---
# setup ansible to run 
- include: ansible.yml

# Setup the autoscale callback application 
- include: app.yml
  when: ansible_asg_app_setup == true

# Synchronize roles and inventory and playbooks
- include: sync.yml
  when: ansible_asg_local_sync == true
