---
# Basic decommissioning example
- name: Delete asg
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Remove asg config
    local_action: ec2_asg name=worker_asg region="{{aws_region}}"  state=absent
  - name: Remove launch config
    local_action: ec2_lc name=worker_lc region="{{aws_region}}"  state=absent

- name: Delete worker EC2 instances
  #hosts: security_group_worker_fw
  hosts: ec2
  connection: local
  gather_facts: False
  tasks:
  - name: Terminate {{ec2_id}} instance in {{aws_region}}
    local_action: ec2 state=absent region='{{ aws_region }}' instance_ids='{{ec2_id}}' wait=true

- name: Delete security groups
  hosts: localhost
  connection: local
  gather_facts: False
  tasks:
  - name: Take main_fw security group down
    local_action: ec2_group name=worker_fw region="{{aws_region}}" description="worker_fw" state=absent 
